- src/App.tsx
- src/components/BoothItem.tsx
- src/components/BoothRanking.tsx
- src/components/FestivalSentence.tsx
애매하게 잡힌 Padding 과 Margin 을 모두 제거하고, display flex 만 사용하니 모든 기기에 맞는 가운데 정렬이 됐다.
> 모든 기기에 가운데 정렬이 가능하도록 수정

- src/components/BoothItem.tsx
- src/components/BoothRanking.tsx
- src/components/LineUp.tsx
// BAD
> styled.div``
// GOOD
> styled.div``;
// BAD
> const <컴포넌트 이름> =style
// GOOD
> const <컴포넌트 이름> = style
> Component styled 세미콜론 및 공백 누락으로  JSX 보여지는 형태가 이상해지는 점 해결

- .eslintrc.js
- package-lock.json
- package.json
- src/App.tsx
- src/components/BoothItem.tsx
- src/components/BoothRanking.tsx
- src/components/FestivalSentence.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/LineUp.tsx
- src/components/Navbar.tsx
- src/main.tsx
- src/styles/GlobalStyle.ts
- src/styles/Theme.ts
- src/styles/defaultTheme.ts
- src/styles/styled.d.ts
* Footer  를 생성했습니다.
* font  와 margin 의 크기는 모두 rem 과 em 을 주어서 반응형으로 처리했습니다.  (rem 과 em 중에서 어떤 걸 써야 적절하지는 아직 감이 잘 오지 않습니다.)
*  현재 디자인과 달리 양옆으로 여백이 없는 상태입니다. 이는 다른 테스크로 처리하겠습니다.
* 회색은 다른 시안에서도 많이 사용하기 때문에 `defaultTheme.ts` 에 잡아놓았습니다.
> Footer  를 생성하기

- src/components/BoothItem.tsx
* 스크롤을 하더라도 네비바가 고정되도록 했다.
* position: fixed 속성을 이용하였다.
> 네비바가 하단에 고정되도록 했다.

- src/hooks/useCheckScreenWidth.ts
* 화면 사이즈를 줄였을 때 이미지끼리 겹쳐지는 부분이 발생했습니다.
* 고려해야 하는 화면 사이즈를 늘렸습니다.
> 더 많은 디바이스 사이즈를 고려한 라인업 이미지 개수 보여주기

- src/components/FestivalSentence.tsx
- src/hooks/useFetchWords.ts
- src/types/Keyword.ts
* 많이 언급된 단어 10개를 받아와서 출력하고자 했습니다
* useFetch를 이용했습니다
> 한줄외치기에 많이 언급 된 단어들을 서버로부터 받아온다

- src/components/TimeTable/Categories.tsx
- src/components/TimeTable/Category.tsx
- src/components/TimeTable/Header.tsx
* src/components/Header.tsx 파일 안에 Header 에 관한 코드가 모두 있었습니다. 
* 날짜와 D-Day 버튼에 대한 부분을 Categories.tsx 파일로 분리하였고, 그 안에서 D-Day 버튼에 대한 부분을 Category.tsx 파일로 분리하였습니다.
* 코드가 정상적으로 동작하나요?
* 컴포넌트를 더 잘 분리하는 방법이 있을까요?
* 백엔드에서 데이터 받는 부분은 이후에 구현하겠습니다. 그에 따라 헤더에 나오는 숫자도 변경됩니다.
- components/TimeTable
- Header.tsx
- Categories.tsx
- Category.tsx
> TimeTable의 Header의 Category 부분의 코드에서 컴포넌트를 분할했습니다.

- src/components/Layout.tsx
- src/components/Main/FestivalSentence.tsx
- src/components/Main/Footer.tsx
- src/components/Main/Navbar.tsx
> footer 사이즈를 피그마의 사이즈에 맞게 줄였습니다

- src/components/Article.tsx
- src/components/BlurContainer.ts
- src/components/Layout.tsx
- src/components/Main/LineUp.tsx
- src/components/Notice/Header.tsx
- src/components/Profile/HelpSection.tsx
- src/components/TimeTable/FilterableTimeTable.tsx
- src/pages/MainPage.tsx
- src/pages/NoticePage.tsx
- src/pages/ProfilePage.tsx
- src/styles/defaultTheme.ts
> 전체 페이지 사이즈를 600px로 고정

- package.json
> package.json 프로젝트 설명 수정

- src/components/Login/LoginForm.tsx
- src/components/Profile/ProfileSection.tsx
- src/hooks/useAccessToken.ts
- src/hooks/useCheckAccessToken.ts
- src/services/ApiService.ts
* 기존에 있던 카카오 기능을 제거했습니다.
*
*
*
> 기존에 있던 카카오 기능 제거

- src/components/Login/LoginForm.tsx
- src/components/Profile/UserInfo.tsx
- src/hooks/useUserStore.ts
- src/services/ApiService.ts
- src/store/LoginFormStore.ts
- src/store/UserStore.ts
* 로그인하면 유저의 정보를 받아온다
* 로그인하면 유저의 정보를 /user/me에 요청해서 받아옵니다.
* 유저의 정보는 Store로 관리합니다.
* 로그인했을 때 유저의 학번이 화면에 보이나요?
*
> 로그인하면 유저의 정보를 받아온다

- src/components/TimeTable/Schedule.tsx
* 타임테이블 실시간에 따른 하이라이트 처리
* 20:00가 현재 시간이라고 예를 들어보겠습니다. 이때 하이라이트 처리가 되는 테이블은 다음의 두 조건을 가장 먼저 만족합니다.
* '시작 시간이 20:00 보다 이전' 
* '끝나는 시간이 20:00 보다 이후'
* 하이라이트는 실시간으로 체크해서  하이라이트 테이블을 바뀌지 않고, 리렌더링을 하거나 페이지 전환이 있으면 하이라이트 테이블이 업데이트 됩니다.
* 반례가 있거나 이상하다고 생각하면 말씀해주십쇼!
* 하이라이츠가 정상적으로 동작하나요?
* 현재는 테스트를 위해서 기준 시간을 20:00로 잡아놓았지만, 축제 전에는 현재 시각으로 바꿀 것입니다.
> 타임테이블 실시간에 따른 하이라이트 처리

- src/components/TimeTable/Schedule.tsx
* Day3에서만 timetable 블록의 너비가 달라졌습니다.
* 옆에 있는 라인을 지우고 containter 태그에서 flex 속성을 삭제했습니다.
* 타임테이블 화면에 오류가 없는지 봐주세요
*
> 타임테이블 Day3 너비 수정

- index.html
- src/components/Main/FestivalSentence.tsx
- src/hooks/useFetchSentence.tsx
* 백엔드 한 줄 외치기 URL 변경
* 구글 애널리스틱 초기 설정
* HTML 파비콘 설정
*
*
*
> 백엔드 한 줄 외치기 URL 변경

- package-lock.json
- package.json
- src/App.tsx
* Vercel Analytics 코드 삽입
*
*
*
> Vercel에 Analytics 설정

- package.json
* 빌드 시 발생하는 오류 해결
*
* package.json에 아래 코드 삽입
```javascript
"@parcel/resolver-default": {
"packageExports": true
}
```
* [참고문서](https://parceljs.org/blog/v2-9-0/#new-resolver)
> 빌드 시 발생하는 오류 해결

- index.html
- src/services/ApiService.ts
* 로그인을 할 때, URL이 알 수 없다고 나왔습니다.
* 이전에 로그인 할 때 백엔드 URL을 직접 잡았었는데, 백엔드 URL이 바뀌면서 오류가 난 것입니다.
* .env 파일에 잡았던 URL을 쓸 수 있도록 변경하였습니다.
*
*
> 로그인을 위해 잡았던 URL을 env 파일에서 가져오도록 수정

- vercel.json
* Vercel에서 카카오 지도가 불려오지 않음. CORS 이슈로 보임. 
* 아래 코드 추가 [[Enabling CORS using vercel.json](https://vercel.com/guides/how-to-enable-cors#enabling-cors-using-vercel.json)](https://vercel.com/guides/how-to-enable-cors)
```json
"headers": [
{
"source": "/api/(.*)",
"headers": [
{ "key": "Access-Control-Allow-Credentials", "value": "true" },
{ "key": "Access-Control-Allow-Origin", "value": "*" },
{ "key": "Access-Control-Allow-Methods", "value": "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
{ "key": "Access-Control-Allow-Headers", "value": "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" }
]
}
]
```
*
*
> Vercel CORS 아슈 처리

- vercel.json
> Vercel json 파일 충돌 해결

- index.html
> kakao 스크립트 호출 위치 변경

- index.html
- src/components/Main/Word.tsx
- src/hooks/useFetchWords.ts
- src/types/Keyword.ts
* 백엔드 한줄외치기 API 명세서가 변경되어 한줄외치기 데이터가 불러와지지 않음.
* 백엔드 한줄외치기 API 명세서 변경에 맞춰서 코드 수정
*
*
> 백엔드 한줄외치기 API 명세서 변경에 맞춰서 코드 수정

- src/components/GuestBook/GuestBook.tsx
- src/components/Layout.tsx
- src/components/Login/LoginForm.tsx
- src/components/Profile/UserInfo.tsx
- src/hooks/useFetchSentence.tsx
- src/services/ApiService.ts
* 로그인 시에 유저 정보가 바로 불러와지지 않는 버그가 있었습니다.
* 로그인 정보가 불러와지면 다시 업데이트 하도록 useEffect를 추가했습니다.
* 로그인 시에 정보가 바로 불러와져서 화면에 보이는지 확인해주세요 
*
> 로그인 시에 유저 정보가 바로 불러와지지 않는 버그 해결

- src/components/MapDetail/DetailedMapPage.tsx
- src/components/Notice/Header.tsx
* 공지사항과 방명록 헤더의 제목이 가운데에 위치해 있지 않음
* 헤더의 최대너비를 잡아줬습니다.
* 공지사항과 방명록 부분의 헤더를 봐주세요
*
> Header의 너비를 설정하여 title을 가운데 위치하게 한다.

- src/components/MapDetail/DetailedMapPage.tsx
*
* 좋아요 클릭 이벤트 변경
* 좋아요를 누를때마다 빨간색으로 변경되는지 봐주세요
*
> 좋아요를 누를때 빨간색으로 변경된다.

- src/styles/GlobalStyle.ts
* input창을 눌렀을 때 한줄외치기 버튼이 그대로 있습니다.
* input창이 사라지지 않습니다.
* emoji가 happy로 고정되어 있습니다.
* 새로운 한줄외치기가 저장되지 않습니다.
* input창을 누르면 한줄외치기 버튼이 사라집니다.
* input창이 열려있는 상태에서 배경부분을 누르면 input창이 사라집니다.
* 랜덤하게 index를 추출해서 이모지를 선택합니다.
* 바뀐 한줄외치기의 URL로 변경했습니다.
* 한줄외치기 버튼을 누르면 하단 배너가 올라오며 버튼이 사라지고, 하단배너 외의 부분을 누르면 배너가 사라지는 지 확인해주세요.
* 한줄외치기를 작성했을 때 랜덤이모지와 함께 내용이 잘 저장되는지 확인해주세요
* 지금은 안나타나지만 16자 채웠을 때 빨간줄 나타나는 거 어떤지, 입력창의 하단 border의 색을 바꾸는 부분이 필요없다면 코드 수정하겠습니다.
> 방명록페이지의 입력창 동작 수정

- src/styles/GlobalStyle.ts
* 모바일에서 터치 시 파란색 박스가 잡힌다.
* webkit-tab-highlight 속성을 추가해서 링크를 터치했을 때 영역에 생기는 색상을 제어했습니다. 
* webkit-user-select: none을 추가해서 이미지는 클릭할 수 없도록 했습니다.
* 모바일에서 네비바 클릭 시 발생했던 문제가 해결되었는지 봐주세요!
*
> Fix mobile problem

- src/components/MapDetail/DetailedMapPage.tsx
* 부스 디테일에서 댓글, 소개 색깔을 안잡음
* 색깔을 검정으로 잡았슴다
*
*
> 부스 상세보기의 댓글과 부스 소개 글자 색깔 설정함

- src/components/GuestBook/GuestBook.tsx
* 작성한 한줄외치기가 백엔드에 저장되지 않는다.
* 전송하는 데이터에 헤더를 추가했다.
* 새로고침해도 전송한 메세지가 잘 남아있는지 봐주세요. 
*
> 방명록 페이지의 동작을 수정했다

- src/components/Main/FestivalSentence.tsx
* 메인페이지에서 한줄 외치기를 클릭해도 아무 동작이 없었다.
* 메인페이지에서 한줄 외치기를 클릭하면 방명록 페이지로 넘어간다.
*
*
> 메인페이지에서 한줄 외치기를 클릭하면 방명록 페이지로 넘어간다

- src/components/MapDetail/BoothComment.tsx
* 댓글이 아무것도 안적혀있는 부스에 댓글을 추가했을 때 바로 보이지 않음
* fetch된 데이터가 없을때 , 새로운 comment가 없을때로 조건을 추가함
* 체육대학주점부스에 댓글이 아무것도 안달린 상태입니다. 그 부스에다가 댓글을 달아서 확인부탁드려용
*
> 부스 댓글이 없는 경우에도 댓글을 추가하면 바로 보이게 한다.

- src/components/Main/FestivalSentenceItem.tsx
- src/components/Map/BannerContent.tsx
- src/components/Notice/NoticeTitle.tsx
* 지도 페이지에서 필터 컨테이너를 스크롤 하도록 합니다. 이때 지도 리스트를 같이 스크롤 되지 않습니다.
* 지도 페이지에서 필터 컨터이너 부분에 overflow-x를 scroll 주었습니다. 
* 스크롤 동작이 정상적으로 되는지 확인해주세요.
*
> 지도 페이지에서 필터 컨테이너를 스크롤 하도록 한다. 이때 지도 리스트를 같이 스크롤 되지 않는다.

- src/components/MapDetail/DetailedMapPage.tsx
* 부스 디테일 좋아요 글자 색깔 설정한 게 날라갔어요
* 다시 설정했습니다.
* 배포 후 반영됐는지 확인해주세요!
*
> 부스 디테일 좋아요 색깔을 설정한다.

- index.html
* Head에 메타데이터 추가해도, 카카오톡에 링크 공유하기를 했을 때 데이터가 나오지 않았습니다. 
* [메타데이터 정보가 잘 출력되는 사이트](https://www.rallit.com/resumes/174216@haryan96/%ED%95%98%ED%98%84%EC%A4%80)를 참고하여 메타 데이터를 더 추가하였습니다.
*
*
> Head에 메타데이터 추가하기

- src/components/TimeTable/Schedule.tsx
* 현재 시간과 날짜를 비교하지 않고 20:00에 고정시켜둠
* 현재 시간과 날짜를 가져와서 비교하는 코드를 추가함
* 코드에 현재 시간과 날짜를 변경해보면서 테스트해주세요! 지금은 아무것도 하이라이트가 안뜨는게 맞습니다.
*
> 타임테이블페이지에서 현재 시간과 현재 날짜를 비교해서 하이라이트를 준다.

- src/components/BlurContainer.ts
- src/components/Main/BoothItem.tsx
- src/components/Main/BoothRanking.tsx
- src/components/Main/LineUp.tsx
- src/components/Map/BoothList.tsx
- src/components/MapDetail/DetailedMapPage.tsx
- src/components/TimeTable/Lineup.tsx
* 백엔드에 이미지 데이터가 없는 경우 아무것도 안나옴
* 부스 상세보기에서 이미지가 있어도 안나옴
* 부스 상세보기에서 이미지의 윗부분이 짤림
* 라인업, 부스에서 이미지 데이터가 있으면 보여주고 없으면 디폴트 이미지를 보이게 하는 코드로 수정했어요
* 부스 디테일, 부스 리스트, 라인업, 부스 랭킹에 이미지가 없는 게 있는지 봐주세요 
* 부스 디테일에서 부스 이미지의 윗부분이 짤리는지 봐주세요
* 라인업 부분은 백엔드 데이터에 쓰레기값이 들어있어서 오류가 납니다. 그래서 제대로된 코드는 한 후에 주석처리 해놓고, 우선 default 사진으로 무조건 보이는 걸로 했어요. 나중에 제대로 데이터 들어오면 주석부분을 쓰면 될 것 같아요
> 부스, 라인업의 디폴트 이미지 변경 및 설정

- src/components/MapDetail/BoothComment.tsx
* 댓글을 쓰고 난 직후 학번 뒷자리 3자리가 보이는 문제 
* substring과 replace를 이용해 학번의 길이 -3만큼의 문자열  + 학번의 뒷자리 3개를 *로 바꾼 문자열로 변경했습니다.
* 댓글을 쓴 직후 학번이 보이는지 안보이는 지 봐주세요!
*
> 댓글을 쓸 때 학번의 뒷자리 3개를 *로 변경한다.

- src/components/MapDetail/InfoWithIcon.tsx
- src/hooks/useFetchBoothComment.ts
- src/types/Booth.ts
* 부스 별 요일에 대한 정보가 없었음
* 부스별 시간과 위치가 안보였음
* 기존 selectedBooth에서 정보를 찾던 걸 booth(부모 배열에서 정보를 찾는 걸로 변경함
* 부스별 정보가 잘 나오는 지 봐주세요
*
> 부스 별 요일과 정보들을 보여준다.

- src/components/Main/BoothRanking.tsx
* 메인 페이지에서 `실시간 업데이트`를 표시하는 부분이 고정된 텍스트였습니다.
* 매일 바뀔 수 있도록 수정했습니다.
* 정상적으로 출력되는지 확인부탁드립니다!
*
> 실시간 업데이트를 표시하는 부분이 매일 바뀔 수 있도록 수정했습니다.

- src/components/GuestBook/GuestBook.tsx
- src/components/Main/FestivalSentence.tsx
- src/components/MapDetail/BoothComment.tsx
- src/components/Notice/ImageModal.tsx
- src/components/Notice/NoticeBottom.tsx
- src/components/TimeTable/Lineup.tsx
* 클릭할 수 있 곳은 css로 pointer 처리해서 UX적으로 자연스럽게 보이도록 함
* cursor: pointer를 아래에 추가했습니다.
* 공지사항에서 이미지에 커서를 올렸을 때
* 공지사항에서 이미지 상세보기에서 X버튼에 커서를 올렸을 때
* 메인페이지에서 한줄외치기에 커서를 올렸을 때
* 방명록에서 한줄외치기 전송 버튼에 커서를 올렸을 때
* cursor: pointer를 없앴습니다. (클릭이 안되는데 cursor 처리가 되어 있었음)
* 타임테이블에서 라인업 이미지에 커서를 올렸을 때
* 적용이 잘 됐는지 확인해주세요!
* 커서가 더 필요한 부분이 있다면 알려주세요!
* 커서가 불 필요한 부분에 적용 됐다면 알려주세요!
*
> 클릭할 수 있 곳은 css로 pointer 처리해서 UX적으로 자연스럽게 보이도록 함

- src/components/MapDetail/BoothComment.tsx
- src/components/MapDetail/DetailedMapPage.tsx
* 부스상세보기 -> 공유하기 버튼을 누를때 아무런 반응이 일어나지 않음
* 부스 댓글을 작성하려고 할때 토큰 검사를 실시한다.
* input에 입력했을때 토큰 검사를 실시한다.
* 클릭이벤트 추가
* 공유하기 버튼을 눌렀을때 파란색으로 변하는지 봐주세요
* 로그인 전에 댓글을 남길때 버튼이 눌리기 전에 경고창이 뜨는 지 확인해주세요
*
> 부스 상세보기 페이지 관련 기능 개발(공유하기 버튼 및 댓글 )

- src/components/GuestBook/GuestBook.tsx
- src/components/Map/MapLayer.tsx
- src/components/MapDetail/BoothComment.tsx
- src/types/Booth.ts
- src/types/BoothDay.ts
> 댓글의 입력창이 확대되는 부분을 수정했다

- src/components/Map/MapLayer.tsx
- src/types/Booth.ts
- src/types/BoothDay.ts
> 부스의 마커 설정 부분을 수정했다

- src/components/Main/FestivalSentenceItem.tsx
- src/components/Profile/HelpSection.tsx
> 메인페이지의 한줄외치기에 별표를 추가했다

- package-lock.json
- package.json
- src/App.tsx
* 사용자 경로 추적을 위해서 Vercel에서 제공하는 speed insights를 설치 및 적용했습니다.
* [Vercel Speed Insights Quickstart](https://vercel.com/docs/speed-insights/quickstart#)
* 페이지가 정상적으로 동작하는지 확인해주세요!
*
> Vercel에서 제공하는 Speed Insights 설치 및 적용

- src/components/Map/BoothList.tsx
- src/components/Map/MapLayer.tsx
- src/components/MapDetail/InfoWithIcon.tsx
* 부스 상세페이지의 아이콘이 찌그러져 보이는 경우가 있었다.
* 아이콘의 사이즈를 수정했다.
*
*
> 아이콘의 사이즈를 수정했다.

- src/components/Map/MapLayer.tsx
* 같은 위치에 부스가 두 개 있으면 한 개의 부스만 보여집니다.
* 같은 위치에 있는 부스가 모두 보일 수 있도록 수정했습니다.
*
*
> 같은 위치에 부스가 두개 있을 경우 두개를 모두 보여준다

- src/components/Main/Footer.tsx
- src/components/MapDetail/DetailedMapPage.tsx
* 서버 운영 시간, 2023으로 적혀있었습니다.
* 서버 운영 시간을 서버 운영 기간으로 변경했습니다.
* 서버 운영 기간을 2023에서 실제 운영 기간으로 변경했습니다.
* 추가로 콘솔에 스타일 컴포넌트 인자에 $를 붙이지 않아서 오류가 나는 부분을 해결했습니다.
* 서버 운영 기간이 정상적으로 보이는지 확인해주세요!
*
> 서버 운영 시간을 적은 텍스트 값 변경

- src/components/Profile/ProfileSection.tsx
* 갤럭시에서 로그아웃 글자가 깨짐
*  횃불이가 찌뿌된 느낌
* 버튼 너비 조절 
* 횃불이 높이와 너비 조절
* 갤럭시에서 로그아웃 버튼이 깨지는지 봐주세요
*  횃불이 크기가 어떤지 봐주세요
*
> Logout 버튼 너비 조절

- src/components/TimeTable/Lineup.tsx
* 부스 라인업 이미지 보여주기 코드 수정
*
* 부스 라인업 이미지가 잘 불러와지는지 확인해주세요
*
> 부스 라인업 이미지 코드 수정

- package.json
* 배포 후 소스코드가 다 보이는 현상
* GENERATE_SOURCEMAP=false 추가
* 배포 후에 개발자도구에서 소스코드가 안보이는지 확인해주세요
*
> 빌드 후 sourcemap 제거

- src/components/Map/MapLayer.tsx
> 마커의 크기를 수정했다

- src/components/MapDetail/DetailedMapPage.tsx
* 부스디테일 이미지 버튼이 1장일 때도 부스 버튼이 나오는 버그
* 1장일때는 부스 버튼이 안나온다.
* 부스 디테일 부분에서 부스 이미지가 한 장일때 버튼이 안나오는지 봐주세요
*
> 부스이미지가 1장일때는 버튼 표시가 안나온다.

- src/components/Main/LineUp.tsx
> 메인페이지 라인업 이미지

- src/components/Layout.tsx
- src/components/Map/Map.tsx
- src/styles/GlobalStyle.ts
* 이전 페이지로 돌아가면, 이전 페이지의 마지막 위치가 아닌 맨 위로 이동하게 되었음.
* 이전 페이지로 돌아갔을 때, 이전 페이지의 마지막 위치로 부드럽게 이동함.
* 이전 페이지로 돌아갔을 때, 제대로 이전 페이지의 마지막 위치로 가나요?
* 필터를 조작했을 때,  이전 페이지의 마지막 위치로 가면 안되는데 제대로 가만히 있나요?
* 이상한 부분이 있다면 말해주세요!
*
> 이전 페이지로 돌아갔을 때, 이전 페이지의 마지막 위치로 부드럽게 이동한다.

- src/components/Profile/ProfileSection.tsx
* 아직도 width가 얇아보이는 버그 
*
* 더 늘려야할지 봐주세요~
*
> 횃불이 width 늘림

- src/components/MapDetail/DetailedMapPage.tsx
* 부스 상세보기를 클릭했을때 스크롤을 올라가게 한다.
* 
* 부스 상세보기를 클릭했을 때 화면이 가장 위로 올라간다.
*
> 부스디테일을 들어가면 포커스가 위로 올라간다.

- src/components/Profile/HelpSection.tsx
> 친구찾기 기능을 삭제했다

- src/components/Login/LoginForm.tsx
> 로그인 문구를 수정했다

- src/components/Map/BoothList.tsx
- src/components/Map/MapLayer.tsx
- src/components/MapDetail/InfoWithIcon.tsx
1. 사진 크기 줄이기
2. 사진 위 아래와 글 위 아래 맞추기
3. 상세보기 클릭 영역 위 아래 여백 늘리기
4. 지도 부분과 목록 부분과의 간격 삭제
5. 부스 리스트 정보 세로 정렬
*
* map페이지에 들어가서 모두 다 적용됐는지 봐주세요 
*
> 디자이너님 map관련 버그 수정

- src/components/MapDetail/BoothComment.tsx
> 부스 댓글 부분의 디자인을 수정했다

- src/components/Main/FestivalSentence.tsx
- src/pages/MainPage.tsx
* 
*
* 메인페이지에 나오는 한줄외치기가 최신순으로 나오는지 봐주세요
* 메인페이지로 돌아갈때마다 상단으로 자동 스크롤된다.
*
> 메인 한줄외치기 역순으로 변경한다.

- src/components/Map/BoothList.tsx
- src/components/Map/MapLayer.tsx
- src/components/MapDetail/DetailedMapPage.tsx
- src/components/MapDetail/InfoWithIcon.tsx
- src/store/LikeStore.ts
> 부스의 마커보기 버튼을 수정했다

- src/components/Profile/HelpSection.tsx
> 아이콘과 글씨 가운데 정렬

- src/components/Main/LineUp.tsx
> 오늘의 라인업으로 수정

- src/components/TimeTable/Schedule.tsx
> 현재 진행중인 공연 표시 수정

- src/components/Main/LineUp.tsx
- src/components/TimeTable/Schedule.tsx
> 타임테이블 진행중 표시 수정

- src/components/Main/LineUp.tsx
> 라인업을 day3으로 바꾼다

- src/components/Main/Footer.tsx
> 메인 페이지 문구 수정

- README.md
> README.md에 프로젝트 소개 부분을 추가한다
